### ISSUE TITLE
Issue #24 :Fix before issue#22 not showing sights at list

### ISSUE THREAD

**Issue by TsolosT** [texnologiesLogismikou/HappyTraveller#24]
@xaroula @IanMoonee @lamdom @ggiannas 
Meta apo ta merge sas uparxh 8ema k den emfanizei ta sights sto list..vrhte lush ;p

**Comment by lamdom** [comment]
den nomizw to diko mou merge na epirease kapou

**Comment by TsolosT** [comment]
checkare to

**Comment by ggiannas** [comment]
DONE
